#!/usr/bin/env python3
"""Generate the human-readable workflow contract from agent-catalog.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "plugins/codex-copilot/agent-catalog.json"
OUTPUT = ROOT / "plugins/codex-copilot/skills/protocol/references/generated-workflows.md"


def render() -> str:
    catalog = json.loads(CATALOG.read_text())
    labels = {
        "bug": "Defect",
        "technical_feature": "Technical feature",
        "experience_feature": "Experience feature",
        "physical_digital_feature": "Physical-digital feature",
        "ui_polish": "UI polish",
        "security_sensitive": "Security-sensitive feature",
        "infrastructure": "Infrastructure",
    }
    lines = [
        "# Generated Workflow Contract",
        "",
        "<!-- Generated by scripts/generate-routing.py from agent-catalog.json. Do not edit by hand. -->",
        "",
        f"Primary entrypoint: `${catalog['entrypoints']['primary']}`  ",
        f"Delegation entrypoint: `${catalog['entrypoints']['launcher']}`",
        "",
        "| Request type | Specialist sequence |",
        "| --- | --- |",
    ]
    for key, sequence in catalog["workflows"].items():
        lines.append(f"| {labels.get(key, key.replace('_', ' ').title())} | `{' -> '.join(sequence)}` |")
    lines.extend(["", "## Routing edges", ""])
    for edge in catalog["routingEdges"]:
        lines.append(f"- `{edge['from']} -> {edge['to']}` when {edge['when']}.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(f"Generated routing is stale: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("Generated routing is current")
        return 0
    OUTPUT.write_text(expected)
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
